inherit_from: .rubocop_todo.yml

# Files to exclude - all executable dependencies from Rubygems.
AllCops:
  Exclude:
    - 'bin/*'

# Give us... a little more room.
Metrics/LineLength:
  Max: 140

# This cop seems to produce a few false-positives.
Style/Next:
  Enabled: false
