sudo: false
cache: bundler
language: ruby
os:
  - osx
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
before_install: gem update --remote bundler
install:
  - bundle install --retry=3
script:
  - bundle exec rspec
  - bundle exec rubocop
