os:
  - osx
language: ruby
cache: bundler
rvm:
  - 2.0.0
  - 2.1.2
  - 2.1.3
before_install:
  - sudo gem install bundler
script:
  - bundle exec rspec
  - bundle exec rubocop lib exe objc-referee.gemspec spec
