/** THIS FILE IS AUTOGENERATED. DO NOT EDIT. CHANGES WILL BE DESTROYED. */

import Foundation
import UIKit

struct Resources {
    static let Storyboards = _Storyboards()
    static let ViewControllers = _ViewControllers()

    /// UIStoryboard accessors.
    struct _Storyboards {
        {{# storyboards #}}
        {{{ swift_implementation }}}
        {{/ storyboards }}
    }

    /// UITableViewCell identifier accessors.
    {{# has_table_cells #}}
    enum TableViewCells: String, CustomStringConvertible {
        {{# table_cells #}}
        {{{ swift_implementation }}}
        {{/ table_cells }}
        var description: String { return rawValue }
    }
    {{/ has_table_cells }}

    /// UICollectionViewCell identifier accessors.
    {{# has_collection_cells }}
    enum CollectionViewCells: String, CustomStringConvertible {
        {{# collection_cells #}}
        {{{ swift_implementation }}}
        {{/ collection_cells }}
        var description: String { return rawValue }
    }
    {{/ has_collection_cells }}

    /// UIViewController accessors.
    struct _ViewControllers {
        {{# view_controllers #}}
        {{{ swift_implementation }}}
        {{/ view_controllers }}
    }

    /// Segue accessors.
    {{# has_segues }}
    enum Segues: String, CustomStringConvertible {
        {{# segues #}}
        {{{ swift_implementation }}}
        {{/ segues }}
        var description: String { return rawValue }
    }
    {{/ has_segues }}
}
