/** THIS FILE IS AUTOGENERATED. DO NOT EDIT. CHANGES WILL BE DESTROYED. */

import Foundation
import UIKit

struct Resources {
    static let Storyboards = _Storyboards()
    static let ViewControllers = _ViewControllers()

    /// UIStoryboard accessors.
    struct _Storyboards {
        {{# storyboards #}}
        {{{ swift_implementation }}}
        {{/ storyboards }}
    }

    /// UITableViewCell identifier accessors.
    enum TableViewCells: String {
        {{# table_cells #}}
        {{{ swift_implementation }}}
        {{/ table_cells }}
    }

    /// UICollectionViewCell identifier accessors.
    enum CollectionViewCells: String {
        {{# collection_cells #}}
        {{{ swift_implementation }}}
        {{/ collection_cells }}
    }

    /// UIViewController accessors.
    struct _ViewControllers {
        {{# view_controllers #}}
        {{{ swift_implementation }}}
        {{/ view_controllers }}
    }

    /// Segue accessors.
    enum Segues: String {
        {{# segues #}}
        {{{ swift_implementation }}}
        {{/ segues }}
    }
}
