#!/usr/bin/env ruby
# Find path to our installed source code.
require 'pathname'
file_path = Pathname.new(__FILE__).realpath
$LOAD_PATH.unshift(File.expand_path('../../rubylib', file_path))

# Require main module and execute CLI.
require 'robjc'
RObjc::CLI.new(ARGV).execute
